repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.4.0
      hooks:
      - id: flake8
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  -   repo: https://github.com/ambv/black
      rev: stable
      hooks:
      - id: black
        language_version: python3.7
  -   repo: https://github.com/asottile/reorder_python_imports
      rev: v2.3.5
      hooks:
      -   id: reorder-python-imports
